name: Issue assignment

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Auto-assign issue"
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: tuxpeople
